title: Sylvia Henry Data Analytics Portfolio
logo: Sylvia Heany Headshot 2.png
description: With Over two years of experience in Data Analystics. Proficent with the use of Adncance Excel, SQL and PowerBI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
